// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALow8ZAhUWLBk2OIXeW95A-Ou1_NKzG84',
    appId: '1:354063573130:web:600730b0203092f7368d73',
    messagingSenderId: '354063573130',
    projectId: 'firebasetestdb',
    authDomain: 'fir-testdb-f6ad0.firebaseapp.com',
    storageBucket: 'firebasetestdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAytymBCQnUSDcSS3HrnXPhHIwB4_v3SNI',
    appId: '1:354063573130:android:ca6cc96eabb976c5368d73',
    messagingSenderId: '354063573130',
    projectId: 'firebasetestdb',
    storageBucket: 'firebasetestdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwuHuLfn2zZI3cEagaZKE1DovENWCQZFQ',
    appId: '1:354063573130:ios:b2301d6c2465c18a368d73',
    messagingSenderId: '354063573130',
    projectId: 'firebasetestdb',
    storageBucket: 'firebasetestdb.appspot.com',
    iosClientId: '354063573130-726645uf242vnecbjt7qo366qbtae1tv.apps.googleusercontent.com',
    iosBundleId: 'com.encode.firebaseloginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwuHuLfn2zZI3cEagaZKE1DovENWCQZFQ',
    appId: '1:354063573130:ios:b2301d6c2465c18a368d73',
    messagingSenderId: '354063573130',
    projectId: 'firebasetestdb',
    storageBucket: 'firebasetestdb.appspot.com',
    iosClientId: '354063573130-726645uf242vnecbjt7qo366qbtae1tv.apps.googleusercontent.com',
    iosBundleId: 'com.encode.firebaseloginapp',
  );
}
